// Generated by scripts/generate-share-codec-model.mjs.
// ABI WARNING: changing this data requires a new URL prefix/codec version.
import model from './shareCodecModelV1.json';
import type { ShareCodecModelV1 } from './shareCodecV3.ts';
export const MODEL_SOURCE_SHA = "8590ae556bfdb69fdb967941cc4bf43f7f4c2902";
export const SHARE_CODEC_MODEL_V1: ShareCodecModelV1 = model;
